version: '2'
services:
  web_front:
    build: .
    ports: 
      - "3001:3000"
    volumes:
      - ../:/code
    entrypoint: yarn docker:run
  couch_front:
    image: "couchdb"
    ports:
      - "5985:5984"